/*
Kagi API

The Kagi API provides programmatic access to data that powers our search results & more.   Get started on the [API Dashboard](https://kagi.com/api) to set up billing, manage API keys, and more.  ### Official Client Libraries  We offer the following libraries you can use to interact with the Kagi API. These are generated from an OpenAPI spec. If you have a language you would like to use and it's not in the list, send us a message and we will add it to the list if it is supported. Or you can use the [spec](https://kagi.redocly.app/_spec/openapi.yaml?download) to build your own custom library.  - [Golang](https://github.com/kagisearch/kagi-openapi-golang) - [Python](https://github.com/kagisearch/kagi-openapi-python) - [TypeScript](https://github.com/kagisearch/kagi-openapi-typescript) - [Rust](https://github.com/kagisearch/kagi-openapi-rust)  ### API Status  **The v1 API is currently in preview to early access testers.**  Our existing API, the \"v0\" beta API, is being replaced with a new version that will be available publicly soon. As changes are made, we will be updating the documentation below when the new features become available.  See the [Support and Community](https://help.kagi.com/kagi/support-and-community/) section for details.  ### Pricing  See our [API Pricing](https://kagi.com/api/pricing) page for standard rates.  ### GitHub Discussions  This is the preferred venue for bug reports and feature requests.  - [Bug Reports](https://github.com/kagisearch/kagi-docs/issues/new/choose) - [Q&A Forum](https://github.com/kagisearch/kagi-docs/discussions/categories/q-a?discussions_q=category%3AQ%26A+label%3Aproduct%3Akagi_search_api) - [API Feature Requests](https://github.com/kagisearch/kagi-docs/discussions/categories/kagi-search-api-feature-requests-ideas)  ### Discord  Join our [Discord](https://kagi.com/discord)! Good for quick questions or chatting about things you've made with our APIs! 

API version: 1
Contact: support@kagi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ErrorEnvelope type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ErrorEnvelope{}

// ErrorEnvelope API error response envelope containing metadata and an array of error details
type ErrorEnvelope struct {
	Meta Meta `json:"meta"`
	// Empty data array when error occurs
	Data []interface{} `json:"data,omitempty"`
	// Array of error detail objects describing what went wrong
	Error []ErrorDetail `json:"error"`
}

type _ErrorEnvelope ErrorEnvelope

// NewErrorEnvelope instantiates a new ErrorEnvelope object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewErrorEnvelope(meta Meta, error_ []ErrorDetail) *ErrorEnvelope {
	this := ErrorEnvelope{}
	this.Meta = meta
	this.Error = error_
	return &this
}

// NewErrorEnvelopeWithDefaults instantiates a new ErrorEnvelope object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewErrorEnvelopeWithDefaults() *ErrorEnvelope {
	this := ErrorEnvelope{}
	return &this
}

// GetMeta returns the Meta field value
func (o *ErrorEnvelope) GetMeta() Meta {
	if o == nil {
		var ret Meta
		return ret
	}

	return o.Meta
}

// GetMetaOk returns a tuple with the Meta field value
// and a boolean to check if the value has been set.
func (o *ErrorEnvelope) GetMetaOk() (*Meta, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Meta, true
}

// SetMeta sets field value
func (o *ErrorEnvelope) SetMeta(v Meta) {
	o.Meta = v
}

// GetData returns the Data field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ErrorEnvelope) GetData() []interface{} {
	if o == nil {
		var ret []interface{}
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ErrorEnvelope) GetDataOk() ([]interface{}, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ErrorEnvelope) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []interface{} and assigns it to the Data field.
func (o *ErrorEnvelope) SetData(v []interface{}) {
	o.Data = v
}

// GetError returns the Error field value
func (o *ErrorEnvelope) GetError() []ErrorDetail {
	if o == nil {
		var ret []ErrorDetail
		return ret
	}

	return o.Error
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
func (o *ErrorEnvelope) GetErrorOk() ([]ErrorDetail, bool) {
	if o == nil {
		return nil, false
	}
	return o.Error, true
}

// SetError sets field value
func (o *ErrorEnvelope) SetError(v []ErrorDetail) {
	o.Error = v
}

func (o ErrorEnvelope) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ErrorEnvelope) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["meta"] = o.Meta
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	toSerialize["error"] = o.Error
	return toSerialize, nil
}

func (o *ErrorEnvelope) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"meta",
		"error",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varErrorEnvelope := _ErrorEnvelope{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varErrorEnvelope)

	if err != nil {
		return err
	}

	*o = ErrorEnvelope(varErrorEnvelope)

	return err
}

type NullableErrorEnvelope struct {
	value *ErrorEnvelope
	isSet bool
}

func (v NullableErrorEnvelope) Get() *ErrorEnvelope {
	return v.value
}

func (v *NullableErrorEnvelope) Set(val *ErrorEnvelope) {
	v.value = val
	v.isSet = true
}

func (v NullableErrorEnvelope) IsSet() bool {
	return v.isSet
}

func (v *NullableErrorEnvelope) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableErrorEnvelope(val *ErrorEnvelope) *NullableErrorEnvelope {
	return &NullableErrorEnvelope{value: val, isSet: true}
}

func (v NullableErrorEnvelope) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableErrorEnvelope) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


