/*
Kagi API

The Kagi API provides programmatic access to data that powers our search results & more.   Get started on the [API Dashboard](https://kagi.com/api) to set up billing, manage API keys, and more.  ### Official Client Libraries  We offer the following libraries you can use to interact with the Kagi API. These are generated from an OpenAPI spec. If you have a language you would like to use and it's not in the list, send us a message and we will add it to the list if it is supported. Or you can use the [spec](https://kagi.redocly.app/_spec/openapi.yaml?download) to build your own custom library.  - [Golang](https://github.com/kagisearch/kagi-openapi-golang) - [Python](https://github.com/kagisearch/kagi-openapi-python) - [TypeScript](https://github.com/kagisearch/kagi-openapi-typescript) - [Rust](https://github.com/kagisearch/kagi-openapi-rust)  ### API Status  **The v1 API is currently in preview to early access testers.**  Our existing API, the \"v0\" beta API, is being replaced with a new version that will be available publicly soon. As changes are made, we will be updating the documentation below when the new features become available.  See the [Support and Community](https://help.kagi.com/kagi/support-and-community/) section for details.  ### Pricing  See our [API Pricing](https://kagi.com/api/pricing) page for standard rates.  ### GitHub Discussions  This is the preferred venue for bug reports and feature requests.  - [Bug Reports](https://github.com/kagisearch/kagi-docs/issues/new/choose) - [Q&A Forum](https://github.com/kagisearch/kagi-docs/discussions/categories/q-a?discussions_q=category%3AQ%26A+label%3Aproduct%3Akagi_search_api) - [API Feature Requests](https://github.com/kagisearch/kagi-docs/discussions/categories/kagi-search-api-feature-requests-ideas)  ### Discord  Join our [Discord](https://kagi.com/discord)! Good for quick questions or chatting about things you've made with our APIs! 

API version: v1 (Preview)
Contact: support@kagi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SearchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchRequest{}

// SearchRequest Used to upload the search query
type SearchRequest struct {
	// Search query to run.
	Query string `json:"query"`
	// Type of results to return.
	Workflow *string `json:"workflow,omitempty"`
	// **(EXPERIMENTAL)** Format to serialize the API response as. The exact contents and structure of markdown output is still being worked on - please send your feedback!
	Format *string `json:"format,omitempty"`
	// Lens to apply to the search. Can be a built-in lens's identifier or a lens ID as shown on https://kagi.com/settings/lenses when a lens is set to be shareable. Can be just the ID portion of the URL (`https://kagi.com/lenses/ID`) or the full URL.
	LensId *string `json:"lens_id,omitempty"`
	Lens *SearchRequestLens `json:"lens,omitempty"`
	// Number of seconds to allow for collecting search results. Lower values will return results more quickly, but may be lower quality or inconsistent between calls. If omitted, will use the latest recommended value by Kagi.
	Timeout *float32 `json:"timeout,omitempty"`
	// Page number for paginated results. Must be between 1 and 10.
	Page *int32 `json:"page,omitempty"`
	// Maximum number of results to return. Must be between 1 and 1024.
	Limit *int32 `json:"limit,omitempty"`
	Filters *SearchRequestFilters `json:"filters,omitempty"`
	Extract *SearchRequestExtract `json:"extract,omitempty"`
	// Whether safe search is enabled, omitting potentially NSFW content.
	SafeSearch *bool `json:"safe_search,omitempty"`
	Personalizations *SearchRequestPersonalizations `json:"personalizations,omitempty"`
}

type _SearchRequest SearchRequest

// NewSearchRequest instantiates a new SearchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchRequest(query string) *SearchRequest {
	this := SearchRequest{}
	this.Query = query
	var workflow string = "search"
	this.Workflow = &workflow
	var format string = "json"
	this.Format = &format
	var safeSearch bool = true
	this.SafeSearch = &safeSearch
	return &this
}

// NewSearchRequestWithDefaults instantiates a new SearchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchRequestWithDefaults() *SearchRequest {
	this := SearchRequest{}
	var workflow string = "search"
	this.Workflow = &workflow
	var format string = "json"
	this.Format = &format
	var safeSearch bool = true
	this.SafeSearch = &safeSearch
	return &this
}

// GetQuery returns the Query field value
func (o *SearchRequest) GetQuery() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Query
}

// GetQueryOk returns a tuple with the Query field value
// and a boolean to check if the value has been set.
func (o *SearchRequest) GetQueryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Query, true
}

// SetQuery sets field value
func (o *SearchRequest) SetQuery(v string) {
	o.Query = v
}

// GetWorkflow returns the Workflow field value if set, zero value otherwise.
func (o *SearchRequest) GetWorkflow() string {
	if o == nil || IsNil(o.Workflow) {
		var ret string
		return ret
	}
	return *o.Workflow
}

// GetWorkflowOk returns a tuple with the Workflow field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchRequest) GetWorkflowOk() (*string, bool) {
	if o == nil || IsNil(o.Workflow) {
		return nil, false
	}
	return o.Workflow, true
}

// HasWorkflow returns a boolean if a field has been set.
func (o *SearchRequest) HasWorkflow() bool {
	if o != nil && !IsNil(o.Workflow) {
		return true
	}

	return false
}

// SetWorkflow gets a reference to the given string and assigns it to the Workflow field.
func (o *SearchRequest) SetWorkflow(v string) {
	o.Workflow = &v
}

// GetFormat returns the Format field value if set, zero value otherwise.
func (o *SearchRequest) GetFormat() string {
	if o == nil || IsNil(o.Format) {
		var ret string
		return ret
	}
	return *o.Format
}

// GetFormatOk returns a tuple with the Format field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchRequest) GetFormatOk() (*string, bool) {
	if o == nil || IsNil(o.Format) {
		return nil, false
	}
	return o.Format, true
}

// HasFormat returns a boolean if a field has been set.
func (o *SearchRequest) HasFormat() bool {
	if o != nil && !IsNil(o.Format) {
		return true
	}

	return false
}

// SetFormat gets a reference to the given string and assigns it to the Format field.
func (o *SearchRequest) SetFormat(v string) {
	o.Format = &v
}

// GetLensId returns the LensId field value if set, zero value otherwise.
func (o *SearchRequest) GetLensId() string {
	if o == nil || IsNil(o.LensId) {
		var ret string
		return ret
	}
	return *o.LensId
}

// GetLensIdOk returns a tuple with the LensId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchRequest) GetLensIdOk() (*string, bool) {
	if o == nil || IsNil(o.LensId) {
		return nil, false
	}
	return o.LensId, true
}

// HasLensId returns a boolean if a field has been set.
func (o *SearchRequest) HasLensId() bool {
	if o != nil && !IsNil(o.LensId) {
		return true
	}

	return false
}

// SetLensId gets a reference to the given string and assigns it to the LensId field.
func (o *SearchRequest) SetLensId(v string) {
	o.LensId = &v
}

// GetLens returns the Lens field value if set, zero value otherwise.
func (o *SearchRequest) GetLens() SearchRequestLens {
	if o == nil || IsNil(o.Lens) {
		var ret SearchRequestLens
		return ret
	}
	return *o.Lens
}

// GetLensOk returns a tuple with the Lens field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchRequest) GetLensOk() (*SearchRequestLens, bool) {
	if o == nil || IsNil(o.Lens) {
		return nil, false
	}
	return o.Lens, true
}

// HasLens returns a boolean if a field has been set.
func (o *SearchRequest) HasLens() bool {
	if o != nil && !IsNil(o.Lens) {
		return true
	}

	return false
}

// SetLens gets a reference to the given SearchRequestLens and assigns it to the Lens field.
func (o *SearchRequest) SetLens(v SearchRequestLens) {
	o.Lens = &v
}

// GetTimeout returns the Timeout field value if set, zero value otherwise.
func (o *SearchRequest) GetTimeout() float32 {
	if o == nil || IsNil(o.Timeout) {
		var ret float32
		return ret
	}
	return *o.Timeout
}

// GetTimeoutOk returns a tuple with the Timeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchRequest) GetTimeoutOk() (*float32, bool) {
	if o == nil || IsNil(o.Timeout) {
		return nil, false
	}
	return o.Timeout, true
}

// HasTimeout returns a boolean if a field has been set.
func (o *SearchRequest) HasTimeout() bool {
	if o != nil && !IsNil(o.Timeout) {
		return true
	}

	return false
}

// SetTimeout gets a reference to the given float32 and assigns it to the Timeout field.
func (o *SearchRequest) SetTimeout(v float32) {
	o.Timeout = &v
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *SearchRequest) GetPage() int32 {
	if o == nil || IsNil(o.Page) {
		var ret int32
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchRequest) GetPageOk() (*int32, bool) {
	if o == nil || IsNil(o.Page) {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *SearchRequest) HasPage() bool {
	if o != nil && !IsNil(o.Page) {
		return true
	}

	return false
}

// SetPage gets a reference to the given int32 and assigns it to the Page field.
func (o *SearchRequest) SetPage(v int32) {
	o.Page = &v
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *SearchRequest) GetLimit() int32 {
	if o == nil || IsNil(o.Limit) {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchRequest) GetLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.Limit) {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *SearchRequest) HasLimit() bool {
	if o != nil && !IsNil(o.Limit) {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *SearchRequest) SetLimit(v int32) {
	o.Limit = &v
}

// GetFilters returns the Filters field value if set, zero value otherwise.
func (o *SearchRequest) GetFilters() SearchRequestFilters {
	if o == nil || IsNil(o.Filters) {
		var ret SearchRequestFilters
		return ret
	}
	return *o.Filters
}

// GetFiltersOk returns a tuple with the Filters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchRequest) GetFiltersOk() (*SearchRequestFilters, bool) {
	if o == nil || IsNil(o.Filters) {
		return nil, false
	}
	return o.Filters, true
}

// HasFilters returns a boolean if a field has been set.
func (o *SearchRequest) HasFilters() bool {
	if o != nil && !IsNil(o.Filters) {
		return true
	}

	return false
}

// SetFilters gets a reference to the given SearchRequestFilters and assigns it to the Filters field.
func (o *SearchRequest) SetFilters(v SearchRequestFilters) {
	o.Filters = &v
}

// GetExtract returns the Extract field value if set, zero value otherwise.
func (o *SearchRequest) GetExtract() SearchRequestExtract {
	if o == nil || IsNil(o.Extract) {
		var ret SearchRequestExtract
		return ret
	}
	return *o.Extract
}

// GetExtractOk returns a tuple with the Extract field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchRequest) GetExtractOk() (*SearchRequestExtract, bool) {
	if o == nil || IsNil(o.Extract) {
		return nil, false
	}
	return o.Extract, true
}

// HasExtract returns a boolean if a field has been set.
func (o *SearchRequest) HasExtract() bool {
	if o != nil && !IsNil(o.Extract) {
		return true
	}

	return false
}

// SetExtract gets a reference to the given SearchRequestExtract and assigns it to the Extract field.
func (o *SearchRequest) SetExtract(v SearchRequestExtract) {
	o.Extract = &v
}

// GetSafeSearch returns the SafeSearch field value if set, zero value otherwise.
func (o *SearchRequest) GetSafeSearch() bool {
	if o == nil || IsNil(o.SafeSearch) {
		var ret bool
		return ret
	}
	return *o.SafeSearch
}

// GetSafeSearchOk returns a tuple with the SafeSearch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchRequest) GetSafeSearchOk() (*bool, bool) {
	if o == nil || IsNil(o.SafeSearch) {
		return nil, false
	}
	return o.SafeSearch, true
}

// HasSafeSearch returns a boolean if a field has been set.
func (o *SearchRequest) HasSafeSearch() bool {
	if o != nil && !IsNil(o.SafeSearch) {
		return true
	}

	return false
}

// SetSafeSearch gets a reference to the given bool and assigns it to the SafeSearch field.
func (o *SearchRequest) SetSafeSearch(v bool) {
	o.SafeSearch = &v
}

// GetPersonalizations returns the Personalizations field value if set, zero value otherwise.
func (o *SearchRequest) GetPersonalizations() SearchRequestPersonalizations {
	if o == nil || IsNil(o.Personalizations) {
		var ret SearchRequestPersonalizations
		return ret
	}
	return *o.Personalizations
}

// GetPersonalizationsOk returns a tuple with the Personalizations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchRequest) GetPersonalizationsOk() (*SearchRequestPersonalizations, bool) {
	if o == nil || IsNil(o.Personalizations) {
		return nil, false
	}
	return o.Personalizations, true
}

// HasPersonalizations returns a boolean if a field has been set.
func (o *SearchRequest) HasPersonalizations() bool {
	if o != nil && !IsNil(o.Personalizations) {
		return true
	}

	return false
}

// SetPersonalizations gets a reference to the given SearchRequestPersonalizations and assigns it to the Personalizations field.
func (o *SearchRequest) SetPersonalizations(v SearchRequestPersonalizations) {
	o.Personalizations = &v
}

func (o SearchRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["query"] = o.Query
	if !IsNil(o.Workflow) {
		toSerialize["workflow"] = o.Workflow
	}
	if !IsNil(o.Format) {
		toSerialize["format"] = o.Format
	}
	if !IsNil(o.LensId) {
		toSerialize["lens_id"] = o.LensId
	}
	if !IsNil(o.Lens) {
		toSerialize["lens"] = o.Lens
	}
	if !IsNil(o.Timeout) {
		toSerialize["timeout"] = o.Timeout
	}
	if !IsNil(o.Page) {
		toSerialize["page"] = o.Page
	}
	if !IsNil(o.Limit) {
		toSerialize["limit"] = o.Limit
	}
	if !IsNil(o.Filters) {
		toSerialize["filters"] = o.Filters
	}
	if !IsNil(o.Extract) {
		toSerialize["extract"] = o.Extract
	}
	if !IsNil(o.SafeSearch) {
		toSerialize["safe_search"] = o.SafeSearch
	}
	if !IsNil(o.Personalizations) {
		toSerialize["personalizations"] = o.Personalizations
	}
	return toSerialize, nil
}

func (o *SearchRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"query",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSearchRequest := _SearchRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSearchRequest)

	if err != nil {
		return err
	}

	*o = SearchRequest(varSearchRequest)

	return err
}

type NullableSearchRequest struct {
	value *SearchRequest
	isSet bool
}

func (v NullableSearchRequest) Get() *SearchRequest {
	return v.value
}

func (v *NullableSearchRequest) Set(val *SearchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchRequest(val *SearchRequest) *NullableSearchRequest {
	return &NullableSearchRequest{value: val, isSet: true}
}

func (v NullableSearchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


