/*
Kagi API

The Kagi API provides programmatic access to data that powers our search results & more.   Get started on the [API Dashboard](https://kagi.com/api) to set up billing, manage API keys, and more.  ### Official Client Libraries  We offer the following libraries you can use to interact with the Kagi API. These are generated from an OpenAPI spec. If you have a language you would like to use and it's not in the list, send us a message and we will add it to the list if it is supported. Or you can use the [spec](https://kagi.redocly.app/_spec/openapi.yaml?download) to build your own custom library.  - [Golang](https://github.com/kagisearch/kagi-openapi-golang) - [Python](https://github.com/kagisearch/kagi-openapi-python) - [TypeScript](https://github.com/kagisearch/kagi-openapi-typescript) - [Rust](https://github.com/kagisearch/kagi-openapi-rust)  ### API Status  **The v1 API is currently in preview to early access testers.**  Our existing API, the \"v0\" beta API, is being replaced with a new version that will be available publicly soon. As changes are made, we will be updating the documentation below when the new features become available.  See the [Support and Community](https://help.kagi.com/kagi/support-and-community/) section for details.  ### Pricing  See our [API Pricing](https://kagi.com/api/pricing) page for standard rates.  ### GitHub Discussions  This is the preferred venue for bug reports and feature requests.  - [Bug Reports](https://github.com/kagisearch/kagi-docs/issues/new/choose) - [Q&A Forum](https://github.com/kagisearch/kagi-docs/discussions/categories/q-a?discussions_q=category%3AQ%26A+label%3Aproduct%3Akagi_search_api) - [API Feature Requests](https://github.com/kagisearch/kagi-docs/discussions/categories/kagi-search-api-feature-requests-ideas)  ### Discord  Join our [Discord](https://kagi.com/discord)! Good for quick questions or chatting about things you've made with our APIs! 

API version: 1
Contact: support@kagi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SearchRequestPersonalizationsDomainsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchRequestPersonalizationsDomainsInner{}

// SearchRequestPersonalizationsDomainsInner struct for SearchRequestPersonalizationsDomainsInner
type SearchRequestPersonalizationsDomainsInner struct {
	// Domain pattern to personalize (e.g., \"example.com\"). Can also be a tld suffix like \".co.uk\".
	Domain string `json:"domain"`
	// Handling mode for this domain pattern
	Kind string `json:"kind"`
}

type _SearchRequestPersonalizationsDomainsInner SearchRequestPersonalizationsDomainsInner

// NewSearchRequestPersonalizationsDomainsInner instantiates a new SearchRequestPersonalizationsDomainsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchRequestPersonalizationsDomainsInner(domain string, kind string) *SearchRequestPersonalizationsDomainsInner {
	this := SearchRequestPersonalizationsDomainsInner{}
	this.Domain = domain
	this.Kind = kind
	return &this
}

// NewSearchRequestPersonalizationsDomainsInnerWithDefaults instantiates a new SearchRequestPersonalizationsDomainsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchRequestPersonalizationsDomainsInnerWithDefaults() *SearchRequestPersonalizationsDomainsInner {
	this := SearchRequestPersonalizationsDomainsInner{}
	return &this
}

// GetDomain returns the Domain field value
func (o *SearchRequestPersonalizationsDomainsInner) GetDomain() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Domain
}

// GetDomainOk returns a tuple with the Domain field value
// and a boolean to check if the value has been set.
func (o *SearchRequestPersonalizationsDomainsInner) GetDomainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Domain, true
}

// SetDomain sets field value
func (o *SearchRequestPersonalizationsDomainsInner) SetDomain(v string) {
	o.Domain = v
}

// GetKind returns the Kind field value
func (o *SearchRequestPersonalizationsDomainsInner) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *SearchRequestPersonalizationsDomainsInner) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *SearchRequestPersonalizationsDomainsInner) SetKind(v string) {
	o.Kind = v
}

func (o SearchRequestPersonalizationsDomainsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchRequestPersonalizationsDomainsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["domain"] = o.Domain
	toSerialize["kind"] = o.Kind
	return toSerialize, nil
}

func (o *SearchRequestPersonalizationsDomainsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"domain",
		"kind",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSearchRequestPersonalizationsDomainsInner := _SearchRequestPersonalizationsDomainsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSearchRequestPersonalizationsDomainsInner)

	if err != nil {
		return err
	}

	*o = SearchRequestPersonalizationsDomainsInner(varSearchRequestPersonalizationsDomainsInner)

	return err
}

type NullableSearchRequestPersonalizationsDomainsInner struct {
	value *SearchRequestPersonalizationsDomainsInner
	isSet bool
}

func (v NullableSearchRequestPersonalizationsDomainsInner) Get() *SearchRequestPersonalizationsDomainsInner {
	return v.value
}

func (v *NullableSearchRequestPersonalizationsDomainsInner) Set(val *SearchRequestPersonalizationsDomainsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchRequestPersonalizationsDomainsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchRequestPersonalizationsDomainsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchRequestPersonalizationsDomainsInner(val *SearchRequestPersonalizationsDomainsInner) *NullableSearchRequestPersonalizationsDomainsInner {
	return &NullableSearchRequestPersonalizationsDomainsInner{value: val, isSet: true}
}

func (v NullableSearchRequestPersonalizationsDomainsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchRequestPersonalizationsDomainsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


