/*
Kagi API

The Kagi API provides programmatic access to data that powers our search results & more.  Get started on the [API Dashboard](https://kagi.com/api) to set up billing, manage API keys, and more. ### Official Client Libraries We offer the following libraries you can use to interact with the Kagi API. These are generated from an OpenAPI spec. If you have a language you would like to use and it's not in the list, send us a message and we will add it to the list if it is supported. Or you can use the [spec](https://kagi.redocly.app/_spec/openapi.yaml?download) to build your own custom library. - [Golang](https://github.com/kagisearch/kagi-openapi-golang) - [Python](https://github.com/kagisearch/kagi-openapi-python) - [TypeScript](https://github.com/kagisearch/kagi-openapi-typescript) - [Rust](https://github.com/kagisearch/kagi-openapi-rust) ### API Status Our existing API, the \"v0\" beta API, is being replaced with a new version that will be available publicly soon. As changes are made, we will be updating the documentation below when the new features become available. See the [Support and Community](https://help.kagi.com/kagi/support-and-community/) section for details. ### Pricing See our [API Pricing](https://kagi.com/api/pricing) page for standard rates. ### GitHub Discussions This is the preferred venue for bug reports and feature requests. - [Bug Reports](https://github.com/kagisearch/kagi-docs/issues/new/choose) - [Q&A Forum](https://github.com/kagisearch/kagi-docs/discussions/categories/q-a?discussions_q=category%3AQ%26A+label%3Aproduct%3Akagi_search_api) - [API Feature Requests](https://github.com/kagisearch/kagi-docs/discussions/categories/kagi-search-api-feature-requests-ideas) ### Discord Join our [Discord](https://kagi.com/discord)! Good for quick questions or chatting about things you've made with our APIs!

API version: v1
Contact: support@kagi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ExtractRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExtractRequest{}

// ExtractRequest Request body for content extraction
type ExtractRequest struct {
	// Array of pages to extract content from. Must contain 1-10 URLs. Each URL must be a valid HTTPS URL. 
	Pages []PageInput `json:"pages"`
	// Optional timeout in seconds for the extraction operation
	Timeout *float32 `json:"timeout,omitempty"`
	// Response format
	Format *string `json:"format,omitempty"`
}

type _ExtractRequest ExtractRequest

// NewExtractRequest instantiates a new ExtractRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExtractRequest(pages []PageInput) *ExtractRequest {
	this := ExtractRequest{}
	this.Pages = pages
	var format string = "json"
	this.Format = &format
	return &this
}

// NewExtractRequestWithDefaults instantiates a new ExtractRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExtractRequestWithDefaults() *ExtractRequest {
	this := ExtractRequest{}
	var format string = "json"
	this.Format = &format
	return &this
}

// GetPages returns the Pages field value
func (o *ExtractRequest) GetPages() []PageInput {
	if o == nil {
		var ret []PageInput
		return ret
	}

	return o.Pages
}

// GetPagesOk returns a tuple with the Pages field value
// and a boolean to check if the value has been set.
func (o *ExtractRequest) GetPagesOk() ([]PageInput, bool) {
	if o == nil {
		return nil, false
	}
	return o.Pages, true
}

// SetPages sets field value
func (o *ExtractRequest) SetPages(v []PageInput) {
	o.Pages = v
}

// GetTimeout returns the Timeout field value if set, zero value otherwise.
func (o *ExtractRequest) GetTimeout() float32 {
	if o == nil || IsNil(o.Timeout) {
		var ret float32
		return ret
	}
	return *o.Timeout
}

// GetTimeoutOk returns a tuple with the Timeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExtractRequest) GetTimeoutOk() (*float32, bool) {
	if o == nil || IsNil(o.Timeout) {
		return nil, false
	}
	return o.Timeout, true
}

// HasTimeout returns a boolean if a field has been set.
func (o *ExtractRequest) HasTimeout() bool {
	if o != nil && !IsNil(o.Timeout) {
		return true
	}

	return false
}

// SetTimeout gets a reference to the given float32 and assigns it to the Timeout field.
func (o *ExtractRequest) SetTimeout(v float32) {
	o.Timeout = &v
}

// GetFormat returns the Format field value if set, zero value otherwise.
func (o *ExtractRequest) GetFormat() string {
	if o == nil || IsNil(o.Format) {
		var ret string
		return ret
	}
	return *o.Format
}

// GetFormatOk returns a tuple with the Format field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExtractRequest) GetFormatOk() (*string, bool) {
	if o == nil || IsNil(o.Format) {
		return nil, false
	}
	return o.Format, true
}

// HasFormat returns a boolean if a field has been set.
func (o *ExtractRequest) HasFormat() bool {
	if o != nil && !IsNil(o.Format) {
		return true
	}

	return false
}

// SetFormat gets a reference to the given string and assigns it to the Format field.
func (o *ExtractRequest) SetFormat(v string) {
	o.Format = &v
}

func (o ExtractRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExtractRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["pages"] = o.Pages
	if !IsNil(o.Timeout) {
		toSerialize["timeout"] = o.Timeout
	}
	if !IsNil(o.Format) {
		toSerialize["format"] = o.Format
	}
	return toSerialize, nil
}

func (o *ExtractRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"pages",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varExtractRequest := _ExtractRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varExtractRequest)

	if err != nil {
		return err
	}

	*o = ExtractRequest(varExtractRequest)

	return err
}

type NullableExtractRequest struct {
	value *ExtractRequest
	isSet bool
}

func (v NullableExtractRequest) Get() *ExtractRequest {
	return v.value
}

func (v *NullableExtractRequest) Set(val *ExtractRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableExtractRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableExtractRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExtractRequest(val *ExtractRequest) *NullableExtractRequest {
	return &NullableExtractRequest{value: val, isSet: true}
}

func (v NullableExtractRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExtractRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


