/*
Kagi API

The Kagi API provides programmatic access to data that powers our search results & more.  Get started on the [API Dashboard](https://kagi.com/api) to set up billing, manage API keys, and more. ### Official Client Libraries We offer the following libraries you can use to interact with the Kagi API. These are generated from an OpenAPI spec. If you have a language you would like to use and it's not in the list, send us a message and we will add it to the list if it is supported. Or you can use the [spec](https://kagi.redocly.app/_spec/openapi.yaml?download) to build your own custom library. - [Golang](https://github.com/kagisearch/kagi-openapi-golang) - [Python](https://github.com/kagisearch/kagi-openapi-python) - [TypeScript](https://github.com/kagisearch/kagi-openapi-typescript) - [Rust](https://github.com/kagisearch/kagi-openapi-rust) ### API Status Our existing API, the \"v0\" beta API, is being replaced with a new version that will be available publicly soon. As changes are made, we will be updating the documentation below when the new features become available. See the [Support and Community](https://help.kagi.com/kagi/support-and-community/) section for details. ### Pricing See our [API Pricing](https://kagi.com/api/pricing) page for standard rates. ### GitHub Discussions This is the preferred venue for bug reports and feature requests. - [Bug Reports](https://github.com/kagisearch/kagi-docs/issues/new/choose) - [Q&A Forum](https://github.com/kagisearch/kagi-docs/discussions/categories/q-a?discussions_q=category%3AQ%26A+label%3Aproduct%3Akagi_search_api) - [API Feature Requests](https://github.com/kagisearch/kagi-docs/discussions/categories/kagi-search-api-feature-requests-ideas) ### Discord Join our [Discord](https://kagi.com/discord)! Good for quick questions or chatting about things you've made with our APIs!

API version: v1
Contact: support@kagi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SearchRequestPersonalizationsDomainsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchRequestPersonalizationsDomainsInner{}

// SearchRequestPersonalizationsDomainsInner struct for SearchRequestPersonalizationsDomainsInner
type SearchRequestPersonalizationsDomainsInner struct {
	// The domain to personalize (e.g., \"example.com\").
	Domain *string `json:"domain,omitempty"`
	// Bias value to apply to results from this domain.
	Bias *float32 `json:"bias,omitempty"`
}

// NewSearchRequestPersonalizationsDomainsInner instantiates a new SearchRequestPersonalizationsDomainsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchRequestPersonalizationsDomainsInner() *SearchRequestPersonalizationsDomainsInner {
	this := SearchRequestPersonalizationsDomainsInner{}
	return &this
}

// NewSearchRequestPersonalizationsDomainsInnerWithDefaults instantiates a new SearchRequestPersonalizationsDomainsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchRequestPersonalizationsDomainsInnerWithDefaults() *SearchRequestPersonalizationsDomainsInner {
	this := SearchRequestPersonalizationsDomainsInner{}
	return &this
}

// GetDomain returns the Domain field value if set, zero value otherwise.
func (o *SearchRequestPersonalizationsDomainsInner) GetDomain() string {
	if o == nil || IsNil(o.Domain) {
		var ret string
		return ret
	}
	return *o.Domain
}

// GetDomainOk returns a tuple with the Domain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchRequestPersonalizationsDomainsInner) GetDomainOk() (*string, bool) {
	if o == nil || IsNil(o.Domain) {
		return nil, false
	}
	return o.Domain, true
}

// HasDomain returns a boolean if a field has been set.
func (o *SearchRequestPersonalizationsDomainsInner) HasDomain() bool {
	if o != nil && !IsNil(o.Domain) {
		return true
	}

	return false
}

// SetDomain gets a reference to the given string and assigns it to the Domain field.
func (o *SearchRequestPersonalizationsDomainsInner) SetDomain(v string) {
	o.Domain = &v
}

// GetBias returns the Bias field value if set, zero value otherwise.
func (o *SearchRequestPersonalizationsDomainsInner) GetBias() float32 {
	if o == nil || IsNil(o.Bias) {
		var ret float32
		return ret
	}
	return *o.Bias
}

// GetBiasOk returns a tuple with the Bias field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchRequestPersonalizationsDomainsInner) GetBiasOk() (*float32, bool) {
	if o == nil || IsNil(o.Bias) {
		return nil, false
	}
	return o.Bias, true
}

// HasBias returns a boolean if a field has been set.
func (o *SearchRequestPersonalizationsDomainsInner) HasBias() bool {
	if o != nil && !IsNil(o.Bias) {
		return true
	}

	return false
}

// SetBias gets a reference to the given float32 and assigns it to the Bias field.
func (o *SearchRequestPersonalizationsDomainsInner) SetBias(v float32) {
	o.Bias = &v
}

func (o SearchRequestPersonalizationsDomainsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchRequestPersonalizationsDomainsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Domain) {
		toSerialize["domain"] = o.Domain
	}
	if !IsNil(o.Bias) {
		toSerialize["bias"] = o.Bias
	}
	return toSerialize, nil
}

type NullableSearchRequestPersonalizationsDomainsInner struct {
	value *SearchRequestPersonalizationsDomainsInner
	isSet bool
}

func (v NullableSearchRequestPersonalizationsDomainsInner) Get() *SearchRequestPersonalizationsDomainsInner {
	return v.value
}

func (v *NullableSearchRequestPersonalizationsDomainsInner) Set(val *SearchRequestPersonalizationsDomainsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchRequestPersonalizationsDomainsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchRequestPersonalizationsDomainsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchRequestPersonalizationsDomainsInner(val *SearchRequestPersonalizationsDomainsInner) *NullableSearchRequestPersonalizationsDomainsInner {
	return &NullableSearchRequestPersonalizationsDomainsInner{value: val, isSet: true}
}

func (v NullableSearchRequestPersonalizationsDomainsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchRequestPersonalizationsDomainsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


