/*
Kagi API

The Kagi API provides programmatic access to data that powers our search results & more.  Quick start for all APIs: - Create an account at [Kagi](https://kagi.com/signup) - Generate an [API key](https://kagi.com/settings?p=api) - Call the API ### Official Client Libraries We offer the following libraries you can use to interact with the Kagi API. These are generated from an OpenAPI spec. If you have a language you would like to use and it's not in the list, send us a message and we will add it to the list if it is supported. Or you can use the [spec](https://kagi.redocly.app/_spec/openapi.yaml?download) to build your own custom library. - [Golang](https://github.com/kagisearch/kagi-openapi-golang) - [Python](https://github.com/kagisearch/kagi-openapi-python) - [TypeScript](https://github.com/kagisearch/kagi-openapi-typescript) - [Rust](https://github.com/kagisearch/kagi-openapi-rust) ### API Status Our existing API, the \"v0\" beta API, is being replaced with a new version that will be available publicly soon. As changes are made, we will be updating the documentation below when the new features become available. See the [Support and Community](https://help.kagi.com/kagi/support-and-community/) section for details. ### Pricing See our [API Pricing](https://kagi.com/api/pricing) page for standard rates. ### GitHub Discussions This is the preferred venue for bug reports and feature requests. - [Bug Reports](https://github.com/kagisearch/kagi-docs/issues/new/choose) - [Q&A Forum](https://github.com/kagisearch/kagi-docs/discussions/categories/q-a?discussions_q=category%3AQ%26A+label%3Aproduct%3Akagi_search_api) - [API Feature Requests](https://github.com/kagisearch/kagi-docs/discussions/categories/kagi-search-api-feature-requests-ideas) ### Discord Join our [Discord](https://kagi.com/discord)! Good for quick questions or chatting about things you've made with our APIs!

API version: 1.0.0
Contact: support@kagi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SearchRequestPersonalizations type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchRequestPersonalizations{}

// SearchRequestPersonalizations Personalization rules to customize search result ranking. Allows specifying domain biases and regex-based replacements.
type SearchRequestPersonalizations struct {
	// Domain-level personalization rules (maximum 1000 rules). Each rule can boost or lower the ranking of results from specific domains.
	Domains []SearchRequestPersonalizationsDomainsInner `json:"domains,omitempty"`
	// Regex-based personalization rules (maximum 1000 rules, max 1000 bytes per pattern).
	Regexes []SearchRequestPersonalizationsRegexesInner `json:"regexes,omitempty"`
}

// NewSearchRequestPersonalizations instantiates a new SearchRequestPersonalizations object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchRequestPersonalizations() *SearchRequestPersonalizations {
	this := SearchRequestPersonalizations{}
	return &this
}

// NewSearchRequestPersonalizationsWithDefaults instantiates a new SearchRequestPersonalizations object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchRequestPersonalizationsWithDefaults() *SearchRequestPersonalizations {
	this := SearchRequestPersonalizations{}
	return &this
}

// GetDomains returns the Domains field value if set, zero value otherwise.
func (o *SearchRequestPersonalizations) GetDomains() []SearchRequestPersonalizationsDomainsInner {
	if o == nil || IsNil(o.Domains) {
		var ret []SearchRequestPersonalizationsDomainsInner
		return ret
	}
	return o.Domains
}

// GetDomainsOk returns a tuple with the Domains field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchRequestPersonalizations) GetDomainsOk() ([]SearchRequestPersonalizationsDomainsInner, bool) {
	if o == nil || IsNil(o.Domains) {
		return nil, false
	}
	return o.Domains, true
}

// HasDomains returns a boolean if a field has been set.
func (o *SearchRequestPersonalizations) HasDomains() bool {
	if o != nil && !IsNil(o.Domains) {
		return true
	}

	return false
}

// SetDomains gets a reference to the given []SearchRequestPersonalizationsDomainsInner and assigns it to the Domains field.
func (o *SearchRequestPersonalizations) SetDomains(v []SearchRequestPersonalizationsDomainsInner) {
	o.Domains = v
}

// GetRegexes returns the Regexes field value if set, zero value otherwise.
func (o *SearchRequestPersonalizations) GetRegexes() []SearchRequestPersonalizationsRegexesInner {
	if o == nil || IsNil(o.Regexes) {
		var ret []SearchRequestPersonalizationsRegexesInner
		return ret
	}
	return o.Regexes
}

// GetRegexesOk returns a tuple with the Regexes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchRequestPersonalizations) GetRegexesOk() ([]SearchRequestPersonalizationsRegexesInner, bool) {
	if o == nil || IsNil(o.Regexes) {
		return nil, false
	}
	return o.Regexes, true
}

// HasRegexes returns a boolean if a field has been set.
func (o *SearchRequestPersonalizations) HasRegexes() bool {
	if o != nil && !IsNil(o.Regexes) {
		return true
	}

	return false
}

// SetRegexes gets a reference to the given []SearchRequestPersonalizationsRegexesInner and assigns it to the Regexes field.
func (o *SearchRequestPersonalizations) SetRegexes(v []SearchRequestPersonalizationsRegexesInner) {
	o.Regexes = v
}

func (o SearchRequestPersonalizations) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchRequestPersonalizations) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Domains) {
		toSerialize["domains"] = o.Domains
	}
	if !IsNil(o.Regexes) {
		toSerialize["regexes"] = o.Regexes
	}
	return toSerialize, nil
}

type NullableSearchRequestPersonalizations struct {
	value *SearchRequestPersonalizations
	isSet bool
}

func (v NullableSearchRequestPersonalizations) Get() *SearchRequestPersonalizations {
	return v.value
}

func (v *NullableSearchRequestPersonalizations) Set(val *SearchRequestPersonalizations) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchRequestPersonalizations) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchRequestPersonalizations) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchRequestPersonalizations(val *SearchRequestPersonalizations) *NullableSearchRequestPersonalizations {
	return &NullableSearchRequestPersonalizations{value: val, isSet: true}
}

func (v NullableSearchRequestPersonalizations) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchRequestPersonalizations) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


