/*
Kagi API

The Kagi API provides programmatic access to data that powers our search results & more.   Get started on the [API Dashboard](https://kagi.com/api) to set up billing, manage API keys, and more.  ### Official Client Libraries  We offer the following libraries you can use to interact with the Kagi API. These are generated from an OpenAPI spec. If you have a language you would like to use and it's not in the list, send us a message and we will add it to the list if it is supported. Or you can use the [spec](https://kagi.redocly.app/_spec/openapi.yaml?download) to build your own custom library.  - [Golang](https://github.com/kagisearch/kagi-openapi-golang) - [Python](https://github.com/kagisearch/kagi-openapi-python) - [TypeScript](https://github.com/kagisearch/kagi-openapi-typescript) - [Rust](https://github.com/kagisearch/kagi-openapi-rust)  ### API Status  **The v1 API is currently in preview to early access testers.**  Our existing API, the \"v0\" beta API, is being replaced with a new version that will be available publicly soon. As changes are made, we will be updating the documentation below when the new features become available.  See the [Support and Community](https://help.kagi.com/kagi/support-and-community/) section for details.  ### Pricing  See our [API Pricing](https://kagi.com/api/pricing) page for standard rates.  ### GitHub Discussions  This is the preferred venue for bug reports and feature requests.  - [Bug Reports](https://github.com/kagisearch/kagi-docs/issues/new/choose) - [Q&A Forum](https://github.com/kagisearch/kagi-docs/discussions/categories/q-a?discussions_q=category%3AQ%26A+label%3Aproduct%3Akagi_search_api) - [API Feature Requests](https://github.com/kagisearch/kagi-docs/discussions/categories/kagi-search-api-feature-requests-ideas)  ### Discord  Join our [Discord](https://kagi.com/discord)! Good for quick questions or chatting about things you've made with our APIs! 

API version: 1
Contact: support@kagi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ExtractResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExtractResponse{}

// ExtractResponse Response containing extracted content
type ExtractResponse struct {
	Meta Meta `json:"meta"`
	// Array of extracted page content
	Data []PageOutput `json:"data"`
	// Optional array of errors that occurred during extraction
	Errors []ErrorDetail `json:"errors,omitempty"`
}

type _ExtractResponse ExtractResponse

// NewExtractResponse instantiates a new ExtractResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExtractResponse(meta Meta, data []PageOutput) *ExtractResponse {
	this := ExtractResponse{}
	this.Meta = meta
	this.Data = data
	return &this
}

// NewExtractResponseWithDefaults instantiates a new ExtractResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExtractResponseWithDefaults() *ExtractResponse {
	this := ExtractResponse{}
	return &this
}

// GetMeta returns the Meta field value
func (o *ExtractResponse) GetMeta() Meta {
	if o == nil {
		var ret Meta
		return ret
	}

	return o.Meta
}

// GetMetaOk returns a tuple with the Meta field value
// and a boolean to check if the value has been set.
func (o *ExtractResponse) GetMetaOk() (*Meta, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Meta, true
}

// SetMeta sets field value
func (o *ExtractResponse) SetMeta(v Meta) {
	o.Meta = v
}

// GetData returns the Data field value
func (o *ExtractResponse) GetData() []PageOutput {
	if o == nil {
		var ret []PageOutput
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ExtractResponse) GetDataOk() ([]PageOutput, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ExtractResponse) SetData(v []PageOutput) {
	o.Data = v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *ExtractResponse) GetErrors() []ErrorDetail {
	if o == nil || IsNil(o.Errors) {
		var ret []ErrorDetail
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExtractResponse) GetErrorsOk() ([]ErrorDetail, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *ExtractResponse) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []ErrorDetail and assigns it to the Errors field.
func (o *ExtractResponse) SetErrors(v []ErrorDetail) {
	o.Errors = v
}

func (o ExtractResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExtractResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["meta"] = o.Meta
	toSerialize["data"] = o.Data
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	return toSerialize, nil
}

func (o *ExtractResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"meta",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varExtractResponse := _ExtractResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varExtractResponse)

	if err != nil {
		return err
	}

	*o = ExtractResponse(varExtractResponse)

	return err
}

type NullableExtractResponse struct {
	value *ExtractResponse
	isSet bool
}

func (v NullableExtractResponse) Get() *ExtractResponse {
	return v.value
}

func (v *NullableExtractResponse) Set(val *ExtractResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableExtractResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableExtractResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExtractResponse(val *ExtractResponse) *NullableExtractResponse {
	return &NullableExtractResponse{value: val, isSet: true}
}

func (v NullableExtractResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExtractResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


